### ISSUE TITLE
Type issue with counters?

### ISSUE THREAD

**Issue by darioush** [vsmenon/start#10]
This IR: 
method x@1:
method main@5: l1#-4:int
instr 1: enter 0
instr 2: nop
instr 3: wrl
instr 4: ret 0
instr 5: entrypc
instr 6: enter 4
instr 7: count 0
instr 8: count 10
instr 9: ret 0

produces some error when sorting keys to print out. 
Class 'String' has no instance method '>'.

NoSuchMethodError : method not found: '>'
Receiver: "0"
Arguments: [10]
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:19:25)
#1      int.< (dart:core-patch/integers.dart:62:18)
#2      int.compareTo (dart:core-patch/integers.dart:107:14)
#3      Comparable.compare.compare (dart:core/comparable.dart:5:64)
#4      Sort.insertionSort_ (dart:_collection-dev/sort.dart:26:34)
#5      Sort._doSort (dart:_collection-dev/sort.dart:15:21)
#6      Sort.sort (dart:_collection-dev/sort.dart:5:12)
#7      IterableMixinWorkaround.sortList (dart:_collection-dev/iterable.dart:753:14)
#8      List.sort (dart:core-patch/growable_array.dart:262:37)
#9      execute (package:start/starti.dart:648:14)
#10     main (file:///home/darioush/git/start/bin/start.dart:45:26)

Therefore, I'm assuming there is some problem with the types.
changing instr 7 to be instr 7: count 00 magically solves the problem but I guess some type is being inferred incorrectly.

**Comment by kellend-git** [comment]
You can fix it as shown here: https://github.com/melonhead901/start/commit/c951f9f8531efa8e0ca7c1a568abc3e3eb0b5cde. Not sure the underlying cause.

**Comment by vsmenon** [comment]
I landed a fix: https://github.com/vsmenon/start/commit/71ac26c472f241739b491929f70af4d28a124ec0

The problem was due to mixing String and int values in a sort.  I put in a custom sort that puts ints ahead of strings regardless of value.

Kellen: I changed some of your logic around quotes - I'm not sure why you were seeing them in the first place.  You should see '$' at index 0.
